class UserProfile {
  String name;
  String fullName;
  String email;
  String dob;
  double height; // cm
  double weight; // kg
  String lastPeriodStart; // YYYY-MM-DD
  int cycleLength; // days
  int periodLength; // days
  String partnerCode; // 6-digit auto-generated by Supabase
  String role; // 'utama' | 'pasangan'

  UserProfile({
    this.name = '',
    this.fullName = '',
    this.email = '',
    this.dob = '',
    this.height = 0,
    this.weight = 0,
    this.lastPeriodStart = '',
    this.cycleLength = 0,
    this.periodLength = 0,
    this.partnerCode = '',
    this.role = 'utama',
  });

  UserProfile copyWith({
    String? name,
    String? fullName,
    String? email,
    String? dob,
    double? height,
    double? weight,
    String? lastPeriodStart,
    int? cycleLength,
    int? periodLength,
    String? partnerCode,
    String? role,
  }) {
    return UserProfile(
      name: name ?? this.name,
      fullName: fullName ?? this.fullName,
      email: email ?? this.email,
      dob: dob ?? this.dob,
      height: height ?? this.height,
      weight: weight ?? this.weight,
      lastPeriodStart: lastPeriodStart ?? this.lastPeriodStart,
      cycleLength: cycleLength ?? this.cycleLength,
      periodLength: periodLength ?? this.periodLength,
      partnerCode: partnerCode ?? this.partnerCode,
      role: role ?? this.role,
    );
  }

  Map<String, dynamic> toJson() => {
    'name': name,
    'fullName': fullName,
    'email': email,
    'dob': dob,
    'height': height,
    'weight': weight,
    'lastPeriodStart': lastPeriodStart,
    'cycleLength': cycleLength,
    'periodLength': periodLength,
    'partnerCode': partnerCode,
    'role': role,
  };

  factory UserProfile.fromJson(Map<String, dynamic> json) => UserProfile(
    name: json['name'] ?? '',
    fullName: json['fullName'] ?? '',
    email: json['email'] ?? '',
    dob: json['dob'] ?? '',
    height: (json['height'] ?? 0).toDouble(),
    weight: (json['weight'] ?? 0).toDouble(),
    lastPeriodStart: json['lastPeriodStart'] ?? '',
    cycleLength: json['cycleLength'] ?? 0,
    periodLength: json['periodLength'] ?? 0,
    partnerCode: json['partnerCode'] ?? '',
    role: json['role'] ?? 'utama',
  );
}

class HydrationLog {
  final String id;
  final int amount; // ml
  final String time; // e.g. "2:30 PM"
  final String type; // e.g. "Glass of Water"

  HydrationLog({
    required this.id,
    required this.amount,
    required this.time,
    required this.type,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'amount': amount,
    'time': time,
    'type': type,
  };

  factory HydrationLog.fromJson(Map<String, dynamic> json) => HydrationLog(
    id: json['id'] ?? '',
    amount: json['amount'] ?? 0,
    time: json['time'] ?? '',
    type: json['type'] ?? '',
  );
}

class SleepLog {
  final String startTime; // "22:30"
  final String endTime; // "06:45"
  final String quality; // "restless" | "light" | "good" | "deep"
  final int totalMinutes;

  SleepLog({
    required this.startTime,
    required this.endTime,
    required this.quality,
    required this.totalMinutes,
  });

  Map<String, dynamic> toJson() => {
    'startTime': startTime,
    'endTime': endTime,
    'quality': quality,
    'totalMinutes': totalMinutes,
  };

  factory SleepLog.fromJson(Map<String, dynamic> json) => SleepLog(
    startTime: json['startTime'] ?? '',
    endTime: json['endTime'] ?? '',
    quality: json['quality'] ?? 'good',
    totalMinutes: json['totalMinutes'] ?? 0,
  );
}

class DailyLog {
  final String date; // YYYY-MM-DD
  final String? mood; // 'terrible' | 'bad' | 'okay' | 'good' | 'great'
  final List<String> symptoms;
  final int severity; // 1-5
  final String personalNotes;
  final SleepLog? sleep;
  final List<HydrationLog>? hydrationLogs;
  final int hydrationGoal;

  DailyLog({
    required this.date,
    this.mood,
    this.symptoms = const [],
    this.severity = 3,
    this.personalNotes = '',
    this.sleep,
    this.hydrationLogs,
    this.hydrationGoal = 2500,
  });

  DailyLog copyWith({
    String? mood,
    List<String>? symptoms,
    int? severity,
    String? personalNotes,
    SleepLog? sleep,
    List<HydrationLog>? hydrationLogs,
    int? hydrationGoal,
  }) {
    return DailyLog(
      date: date,
      mood: mood ?? this.mood,
      symptoms: symptoms ?? this.symptoms,
      severity: severity ?? this.severity,
      personalNotes: personalNotes ?? this.personalNotes,
      sleep: sleep ?? this.sleep,
      hydrationLogs: hydrationLogs ?? this.hydrationLogs,
      hydrationGoal: hydrationGoal ?? this.hydrationGoal,
    );
  }

  Map<String, dynamic> toJson() => {
    'date': date,
    'mood': mood,
    'symptoms': symptoms,
    'severity': severity,
    'personalNotes': personalNotes,
    'sleep': sleep?.toJson(),
    'hydrationLogs': hydrationLogs?.map((e) => e.toJson()).toList(),
    'hydrationGoal': hydrationGoal,
  };

  factory DailyLog.fromJson(Map<String, dynamic> json) => DailyLog(
    date: json['date'] ?? '',
    mood: json['mood'],
    symptoms: (json['symptoms'] as List?)?.cast<String>() ?? const [],
    severity: json['severity'] ?? 3,
    personalNotes: json['personalNotes'] ?? '',
    sleep: json['sleep'] != null ? SleepLog.fromJson(json['sleep']) : null,
    hydrationLogs: (json['hydrationLogs'] as List?)
        ?.map((e) => HydrationLog.fromJson(e))
        .toList(),
    hydrationGoal: json['hydrationGoal'] ?? 2500,
  );
}

class NotificationSettings {
  bool periodReminder;
  int periodDaysBefore;
  String periodTime;
  bool ovulationReminder;
  bool hydrationReminder;
  String hydrationInterval;
  bool sleepReminder;
  String sleepTime;
  bool symptomReminder;

  NotificationSettings({
    this.periodReminder = true,
    this.periodDaysBefore = 2,
    this.periodTime = '09:00',
    this.ovulationReminder = true,
    this.hydrationReminder = true,
    this.hydrationInterval = 'Every 2 hours',
    this.sleepReminder = true,
    this.sleepTime = '21:30',
    this.symptomReminder = true,
  });

  NotificationSettings copy() {
    return NotificationSettings(
      periodReminder: periodReminder,
      periodDaysBefore: periodDaysBefore,
      periodTime: periodTime,
      ovulationReminder: ovulationReminder,
      hydrationReminder: hydrationReminder,
      hydrationInterval: hydrationInterval,
      sleepReminder: sleepReminder,
      sleepTime: sleepTime,
      symptomReminder: symptomReminder,
    );
  }

  Map<String, dynamic> toJson() => {
    'periodReminder': periodReminder,
    'periodDaysBefore': periodDaysBefore,
    'periodTime': periodTime,
    'ovulationReminder': ovulationReminder,
    'hydrationReminder': hydrationReminder,
    'hydrationInterval': hydrationInterval,
    'sleepReminder': sleepReminder,
    'sleepTime': sleepTime,
    'symptomReminder': symptomReminder,
  };

  factory NotificationSettings.fromJson(Map<String, dynamic> json) =>
      NotificationSettings(
        periodReminder: json['periodReminder'] ?? true,
        periodDaysBefore: json['periodDaysBefore'] ?? 2,
        periodTime: json['periodTime'] ?? '09:00',
        ovulationReminder: json['ovulationReminder'] ?? true,
        hydrationReminder: json['hydrationReminder'] ?? true,
        hydrationInterval: json['hydrationInterval'] ?? 'Every 2 hours',
        sleepReminder: json['sleepReminder'] ?? true,
        sleepTime: json['sleepTime'] ?? '21:30',
        symptomReminder: json['symptomReminder'] ?? true,
      );
}

enum AppLanguage { indonesia, english }

class AppSettings {
  AppLanguage language;

  String theme;
  bool pinLockEnabled;
  bool biometricsEnabled;
  String pinCode;

  AppSettings({
    this.language = AppLanguage.indonesia,
    this.theme = 'light',
    this.pinLockEnabled = true,
    this.biometricsEnabled = true,
    this.pinCode = '1234',
  });

  AppSettings copy() {
    return AppSettings(
      language: language,
      theme: theme,
      pinLockEnabled: pinLockEnabled,
      biometricsEnabled: biometricsEnabled,
      pinCode: pinCode,
    );
  }

  Map<String, dynamic> toJson() => {
    'language': language.name,
    'theme': theme,
    'pinLockEnabled': pinLockEnabled,
    'biometricsEnabled': biometricsEnabled,
    'pinCode': pinCode,
  };

  factory AppSettings.fromJson(Map<String, dynamic> json) => AppSettings(
    language: AppLanguage.values.firstWhere(
      (e) => e.name == json['language'],
      orElse: () => AppLanguage.indonesia,
    ),
    theme: json['theme'] ?? 'light',
    pinLockEnabled: json['pinLockEnabled'] ?? true,
    biometricsEnabled: json['biometricsEnabled'] ?? true,
    pinCode: json['pinCode'] ?? '1234',
  );
}

class PartnerConnection {
  final String id;
  final String requesterId;
  final String receiverId;
  final String status; // 'pending' | 'accepted' | 'rejected'
  final DateTime createdAt;

  PartnerConnection({
    required this.id,
    required this.requesterId,
    required this.receiverId,
    required this.status,
    required this.createdAt,
  });

  factory PartnerConnection.fromJson(Map<String, dynamic> json) =>
      PartnerConnection(
        id: json['id'] ?? '',
        requesterId: json['requester_id'] ?? '',
        receiverId: json['receiver_id'] ?? '',
        status: json['status'] ?? 'pending',
        createdAt: json['created_at'] != null
            ? DateTime.parse(json['created_at'])
            : DateTime.now(),
      );

  Map<String, dynamic> toJson() => {
    'id': id,
    'requester_id': requesterId,
    'receiver_id': receiverId,
    'status': status,
    'created_at': createdAt.toIso8601String(),
  };
}

class PartnerLogBundle {
  final String partnerUserId;
  final String partnerName;
  final List<DailyLog> dailyLogs;
  final List<HydrationLog> hydrationLogs;

  PartnerLogBundle({
    required this.partnerUserId,
    required this.partnerName,
    this.dailyLogs = const [],
    this.hydrationLogs = const [],
  });
}
